a1=int(input("enter your first num:-"))
a2=int(input("enter your second num:-"))
print(a1,a2)
print("sum(a1,a2)=",a1+a2)
print("difference(a1,a2)=",a1-a2)
print("multiple(a1,a2)=",a1*a2)
print("division(a1,a2)=",a1/a2)
print("modulo(a1,a2)=",a1%a2)
print("power(a1,a2)=",a1**a2)
print("floor division(a1,a2)=",a1//a2)